spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: baoisamazing
    url: jdbc:postgresql://localhost:5433/training_material
    username: baonguyen
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

server:
    servlet:
      encoding:
        charset: UTF-8
