spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123
    url: jdbc:postgresql://localhost:5433/training_material
    username: baonguyen
  data:
    mongodb:
      uri: mongodb://baonguyen:123@localhost:27017
      authentication-database: admin
      database: training_material_mongodb
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

server:
    servlet:
      encoding:
        charset: UTF-8
