version: '3.8'

services:
  # Postgres
  postgres:
    image: postgres:14
    environment:
      POSTGRES_MULTIPLE_DATABASES: training_material
      POSTGRES_USER: baonguyen
      POSTGRES_PASSWORD: baoisamazing
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  mongo:
    image: mongo:5-focal
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dev
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: m0ng0p4ssw0rd
    volumes:
      - mongo:/data/db
    restart: unless-stopped

volumes:
  postgres:
  mongo: