version: '3.8'

services:
  # Postgres
  postgres:
    image: postgres:14
    environment:
      POSTGRES_MULTIPLE_DATABASES: training_material
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: p0stgr3sp4ssw0rd
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres: